DROP TABLE IF EXISTS trading_transaction;
DROP TABLE IF EXISTS wallet_balance;
DROP TABLE IF EXISTS aggregated_price;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS trading_pair;

CREATE TABLE trading_pair (
    symbol VARCHAR(20) NOT NULL COMMENT 'Trading pair symbol (e.g. BTCUSDT, ETHUSDT)',
    base_currency VARCHAR(10) NOT NULL COMMENT 'Base asset being traded (e.g. BTC, ETH)',
    quote_currency VARCHAR(10) NOT NULL COMMENT 'Quote currency used for settlement (e.g. USDT)',
    PRIMARY KEY (symbol)
);

CREATE TABLE aggregated_price (
    trading_pair VARCHAR(20) NOT NULL COMMENT 'Trading pair symbol',
    bid_price DECIMAL(19, 8) NOT NULL COMMENT 'Best bid price used for SELL orders',
    ask_price DECIMAL(19, 8) NOT NULL COMMENT 'Best ask price used for BUY orders',
    bid_price_source VARCHAR(50) NOT NULL COMMENT 'Exchange providing the best bid price',
    ask_price_source VARCHAR(50) NOT NULL COMMENT 'Exchange providing the best ask price',
    updated_at TIMESTAMP NOT NULL COMMENT 'Timestamp when the price was last aggregated',
    PRIMARY KEY (trading_pair),
    CONSTRAINT aggregated_price_trading_pair_fk FOREIGN KEY (trading_pair) REFERENCES trading_pair(symbol)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'Surrogate primary key for user',
    username VARCHAR(255) NOT NULL UNIQUE COMMENT 'Unique username for login',
    password VARCHAR(255) COMMENT 'Encrypted user password',
    name VARCHAR(255) NULL COMMENT 'Display name of the user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'User creation timestamp'
);

CREATE TABLE wallet_balance (
    user_id BIGINT NOT NULL COMMENT 'Reference to users.id',
    currency VARCHAR(10) NOT NULL COMMENT 'Currency code (USDT, BTC, ETH)',
    balance DECIMAL(19, 8) NOT NULL COMMENT 'Available balance for the currency',
    version BIGINT NOT NULL COMMENT 'Version for optimistic locking',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Wallet balance creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Last wallet balance update timestamp',
    PRIMARY KEY (user_id, currency),
    CONSTRAINT wallet_balance_user_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE trading_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'Unique trade identifier',
    trading_pair VARCHAR(20) NOT NULL COMMENT 'Trading pair symbol (e.g. BTCUSDT)',
    user_id BIGINT NOT NULL COMMENT 'Reference to users.id',
    trans_type VARCHAR(50) NOT NULL COMMENT 'Trade type: BUY or SELL',
    base_amount DECIMAL(19, 8) NOT NULL COMMENT 'Quantity user trades (ETH/BTC)',
    executed_price DECIMAL(19, 8) NOT NULL COMMENT 'Price from aggregatedPrice (ask/bid)',
    price_source VARCHAR(10) NOT NULL COMMENT 'Exchange providing the execution price',
    quote_amount DECIMAL(19, 8) NOT NULL COMMENT 'Total quote amount (base_amount × executed_price)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Trade execution timestamp',
    CONSTRAINT trading_transaction_user_fk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT trading_transaction_trading_pair_fk FOREIGN KEY (trading_pair) REFERENCES trading_pair(symbol)
);
